import mysql.connector as c
con=c.connect(host="localhost",user="root",passwd="",database="aqeeb")
Cursor=con.cursor()
code=int(input("Enter code:"))
name=input("Enter name:")
design=input("Enter designation:")
salary=int(input("Enter salary:"))
Cursor.execute("INSERT INTO `emp` (`code`, `name`, `design`, `salary`) VALUES (NULL, '{}', '{}', '{}');".format(code,name,design,salary))
con.commit()
print("Successfully Entered")